### ISSUE TITLE
Research tab should stay open so that Harvesters read it

### ISSUE THREAD

**Issue by kmcculloch** [edgi-govdata-archiving/archivers.space#14]
_From @danielballan on February 4, 2017 17:7_

... or at least make it more obvious that the pane is expandable. Via Lou on Slack.

_Copied from original issue: b5/pipeline#38_

**Comment by kmcculloch** [comment]
I think a little triangle icon that toggles to the side to indicate collapsed/expanded would be easy to implement and is a pretty standard UI element.

**Comment by danielballan** [comment]
Sounds right to me.

**Comment by dcwalk** [comment]
Agreed, lets work with existing UI patterns :)

**Comment by kmcculloch** [comment]
This has been merged to master and deployed
