### ISSUE TITLE
Bagging: Add an upload button to upload the bag in the final S3 bucket (IMPORTANT)

### ISSUE THREAD

**Issue by kmcculloch** [edgi-govdata-archiving/archivers.space#17]
_From @khdelphine on February 9, 2017 20:2_

Also remove “Bag Url / Location” → Not useful, right? Or am I missing something?
I mean, why not do the upload directly inside the app, as we do for the Harvesters?

_Copied from original issue: b5/pipeline#47_

**Comment by kmcculloch** [comment]
Was this implemented via the web uploader/upload token part of the interface, or is this something else?

**Comment by khdelphine** [comment]
Yes this done and can be closed.
