### ISSUE TITLE
Add Describers section?

### ISSUE THREAD

**Issue by kmcculloch** [edgi-govdata-archiving/archivers.space#18]
_From @khdelphine on February 9, 2017 20:4_

Add a Describe step before Done? 
It seems to me that it would not be very complicated to do: just add the metadata fields listed here (in Col B) for the Describers to fill out.
If we do that, the Done section could provide pretty much the same view/functionality as CKAN (at least as a short term solution). What do you think?

_Copied from original issue: b5/pipeline#49_

**Comment by kmcculloch** [comment]
_From @khdelphine on February 10, 2017 1:10_

The URL got deleted in my cut and paste:
https://docs.google.com/spreadsheets/d/12JAleU6eF4wgu0hIlQ5efoOUCsZjT-UkRxwAofVZp6c/edit#gid=1879921913

(This is the list of metadata fields we had proposed, originally for the CKAN instance.)

**Comment by kmcculloch** [comment]
_From @khdelphine on February 14, 2017 12:47_

@b5, any update on this, by any chance? I discussed with @librlaurie that CKAN is ready for us to create records in it. But we need a way to keep track of which URL got a CKAN record created and which one did not. [See next comment as to how that could minimally look.] Thanks.

**Comment by kmcculloch** [comment]
_From @khdelphine on February 14, 2017 13:24_

@b5 Here is a tentative description of how the Archivers app should work for a minimal implementation of the Describer phase: https://github.com/datarefuge/workflow/blob/App-driven-updates-2017-02-14/metadata.md

Basically: 
* Have a "Describe" phase that would show the URLs currently appearing under "Done"
* It should include a "CKAN URL" field
* And have a checkbox to make the Describe phase as done.

Note that, as a result, the Done phase would now show the URLs that have been Described.

How does that sound?

**Comment by kmcculloch** [comment]
I believe @b5 implemented this last week. Is it deployed?

**Comment by khdelphine** [comment]
Yes, this is done an can be closed. Yay!
