### ISSUE TITLE
Clarify "can it be crawled?" language under Research

### ISSUE THREAD

**Issue by kmcculloch** [edgi-govdata-archiving/archivers.space#29]
_From @dcwalk on February 12, 2017 2:21_

From #54:

> remove the "can it be crawled?" language, and make this flag an explicit Do not harvest option, meaning this url contains no harvestable information, and should be ignored.

_Copied from original issue: b5/pipeline#64_

**Comment by kmcculloch** [comment]
Page currently reads "Do not harvest. All data is small, unstructured, and on a page crawlable by the Internet Archive." I'm making a "Fixed/No Longer Needed?" label for issues that I think might be stale.

**Comment by danielballan** [comment]
I think this is safe to close. I put in the current wording and the numerous checkboxes in response to this issue. This needs to be revisited in a broader sense (aligned with other metadata schemas, including our own Chrome extension) but that's a separate issue.

**Comment by dcwalk** [comment]
Yeah this looks fixed! 👍
