### ISSUE TITLE
Make stage complete checkboxes more obvious

### ISSUE THREAD

**Issue by janetriley** [edgi-govdata-archiving/archivers.space#38]
The mark-complete checkboxes are easy to overlook.  

I didn't know we were supposed to check them to signal a stage was done, and just checked the URL back in.   Judging by other tickets in the pipeline, others are making the same mistake; they have notes about what they harvested but are still open. 

Perhaps label the checkbox, or put the checkbox beside the section header.

**Comment by kmcculloch** [comment]
I think we should add a label at a minimum. We should also emphasize the checkbox in documentation and training.

I've added an issue to discuss other ideas for making the workflow UI more intuitive here: https://github.com/edgi-govdata-archiving/archivers.space/issues/46

**Comment by kmcculloch** [comment]
There's a cleanup task in the queue for fixing URLs where the user forgot to check the box: https://github.com/edgi-govdata-archiving/archivers.space/issues/36

**Comment by kmcculloch** [comment]
This has been merged to master and deployed
