### ISSUE TITLE
add "Data Rescue Twin Cities"

### ISSUE THREAD

**Issue by jschell42** [edgi-govdata-archiving/archivers.space#4]
can you add an option for "Data Rescue Twin Cities" on the list that you use to generate invites? we need to start adding guides for the event this weekend. also, can you put that on the list of events? Friday 11-6, Saturday 10-6. thanks!

**Comment by kmcculloch** [comment]
@jschell42 I posted this ticket to the archivers slack team. I'm not sure who does onboarding support for event organizers, but I'll try to make sure your request gets routed to the right place.

**Comment by kmcculloch** [comment]
@jschell42 You might want to join the archivers slack team yourself, too: It's the best place to get app support as you prepare your event. https://archivers-slack.herokuapp.com/

**Comment by jschell42** [comment]
@kmcculloch thanks! i'm already on it, just trying to figure out the best way to submit things like this (direct ask in a slack channel vs. github issue vs. whatever else)

**Comment by b5** [comment]
I worked this out with @jschell42 over slack! Admins on archivers.space are able to create events.

**Comment by titaniumbones** [comment]
argh, that means I could have done it! Sorry!

Maybe we can start writing some documentation in the issues-only repo?
(not you, but maybe me and dawn when we get a chance).

**Comment by b5** [comment]
or maybe we can make it an agenda item at this meeting to have an official docs maintainer that isn't one of you two ;) ?
