### ISSUE TITLE
Broken "Download Zip Starter" for a particular URL

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/archivers.space#43]
I can reproduce an issue reported on Slack: clicking the "Download Zip Starter" button does nothing for this particular URL.

http://www.archivers.space/urls/40B56E61-11C5-42E9-B440-49E5B164A80C

The resource was checked out and the Research phase was marked complete.

**Comment by efran** [comment]
Having a similar issue with 

[http://www.archivers.space/urls/BC201A4E-D9A9-455D-B852-BAE54A9222A6](http://www.archivers.space/urls/BC201A4E-D9A9-455D-B852-BAE54A9222A6)

**Comment by kmcculloch** [comment]
@danielballan @efran Need help triaging this: is this happening often? Any theories on why? Is there a reasonable manual workaround we could add to the FAQ page, such as "if this happens, say so in the harvest notes and add the URL again?"

**Comment by danielballan** [comment]
My theory is that one of the entries that creates the JSON is malformed in some way, but I could not quickly spot the culprit. I'm only aware of these two occurrences.

**Comment by b5** [comment]
All fix. See [here](https://github.com/edgi-govdata-archiving/zip-starter/issues/6)
