### ISSUE TITLE
400 Response for Zip Starter download button

### ISSUE THREAD

**Issue by jasonnance** [edgi-govdata-archiving/archivers.space#58]
Clicking the "Download Zip Starter" button for some UUIDs does nothing; the browser console shows the following request/response failure.

### Request:
URL: ```POST http://zip-starter.herokuapp.com/```
Headers:
```Host: zip-starter.herokuapp.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://www.archivers.space/urls/FA38C827-D488-424D-92DE-BB17B553DD6F
Content-Type: application/json
Content-Length: 4560
Origin: http://www.archivers.space
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```
Body:
```{"url":"https://mrlc.gov","Individual source or seed URL":"https://mrlc.gov","UUID":"FA38C827-D488-424D-92DE-BB17B553DD6F","Institution facilitating the data capture creation and packaging":"","Date of capture":"Sat Mar 04 2017 14:39:20 GMT-0500 (EST)","Name of resource":"","title":"Multi-Resolution Lan Characteristics Consortium (MRLC) -- National Land Cover Database","File formats contained in package":"zip files -- SHP files","Type(s) of content in package":"National Land Cover Database 2011 (NLCD 2011) is the most recent national land cover product created by the Multi-Resolution Land Characteristics (MRLC) Consortium. NLCD 2011 provides - for the first time - the capability to assess wall-to-wall, spatially explicit, national land cover changes and trends across the United States from 2001 to 2011. As with two previous NLCD land cover products NLCD 2011 keeps the same 16-class land cover classification scheme that has been applied consistently across the United States at a spatial resolution of 30 meters. NLCD 2011 is based primarily on a decision-tree classification of circa 2011 Landsat satellite data. \n\nThe Multi-Resolution Land Characteristics (MRLC) consortium is a group of federal agencies who coordinate and generate consistent and relevant land cover information at the national scale for a wide variety of environmental, land management, and modeling applications. The creation of this consortium has resulted in the mapping of the lower 48 United States, Hawaii, Alaska and Puerto Rico into a comprehensive land cover product termed, the National Land Cover Database (NLCD), from decadal Landsat satellite imagery and other supplementary datasets.\n\nThe primary objective of the MRLC NLCD is to provide the Nation with nationally complete, current, consistent, and public domain information on the Nation's land cover. Land cover information is critical for local, state, and federal managers and officials to assist them with issues such as assessing ecosystem status and health, modeling nutrient and pesticide runoff, understanding spatial patterns of biodiversity, land use planning, deriving landscape pattern metrics, and developing land management policies.\n\nAll MRLC NLCD data products are available at no charge to the user.","Name of package creator":"jason.nance","significance":"National Land Cover Database 2011 (NLCD 2011) is the most recent national land cover product created by the Multi-Resolution Land Characteristics (MRLC) Consortium. NLCD 2011 provides - for the first time - the capability to assess wall-to-wall, spatially explicit, national land cover changes and trends across the United States from 2001 to 2011. As with two previous NLCD land cover products NLCD 2011 keeps the same 16-class land cover classification scheme that has been applied consistently across the United States at a spatial resolution of 30 meters. NLCD 2011 is based primarily on a decision-tree classification of circa 2011 Landsat satellite data. \n\nThe Multi-Resolution Land Characteristics (MRLC) consortium is a group of federal agencies who coordinate and generate consistent and relevant land cover information at the national scale for a wide variety of environmental, land management, and modeling applications. The creation of this consortium has resulted in the mapping of the lower 48 United States, Hawaii, Alaska and Puerto Rico into a comprehensive land cover product termed, the National Land Cover Database (NLCD), from decadal Landsat satellite imagery and other supplementary datasets.\n\nThe primary objective of the MRLC NLCD is to provide the Nation with nationally complete, current, consistent, and public domain information on the Nation's land cover. Land cover information is critical for local, state, and federal managers and officials to assist them with issues such as assessing ecosystem status and health, modeling nutrient and pesticide runoff, understanding spatial patterns of biodiversity, land use planning, deriving landscape pattern metrics, and developing land management policies.\n\nAll MRLC NLCD data products are available at no charge to the user.","recommended_approach":"USE HTTP:// NOT HTTPS:// \n\nUSE THIS LINK FOR A LIST OF DATABASES -- http://www.mrlc.gov/nlcd2011.php\n\nThere are several DATA DOWNLOADS links on the left navigation bar.\n\nYou will then find lists of multiple large files in each Database (NLCD 2011, NLCD 2006, NLCD 2001, NLCD Scrubland, NLCD-MODIS Land Cover-Albedo Database, NLCD 1992/2001 Retrofit Land Cover Change Product, NLCD 1992)\n\n"}```

### Response:

Headers:
```HTTP/1.1 400 Bad Request
Server: Cowboy
Connection: keep-alive
access-control-allow-headers: Content-Type
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Allow-Origin: *
Date: Sat, 04 Mar 2017 19:39:19 GMT
Content-Length: 375
Content-Type: text/plain; charset=utf-8
Via: 1.1 vegur
```

Body:
    `error fetching url '&{%!s(*zip.header=&{0xc420234460 0}) %!s(*zip.countWriter=&{0xc42022eb40 71}) %!s(*zip.countWriter=&{0xc42045a000 4597}) %!s(*zip.pooledFlateWriter=&{{0 0} 0xc420132000}) %!s(*zip.countWriter=&{0xc4206b8ac0 0}) %!s(*crc32.digest=&{1741387172 0xc42002d000}) %!s(bool=false)}': Get https://mrlc.gov: dial tcp: lookup mrlc.gov on 172.16.0.23:53: no such host`

**Comment by b5** [comment]
Thanks so much for such a clear outline of the problem @jasonnance 

[zip-starter](https://github.com/edgi-govdata-archiving/zip-starter) was reporting as an error & causing the failure. We've [adjusted the behavior of zip-starter](https://github.com/edgi-govdata-archiving/zip-starter/issues/6) to make this work.
