### ISSUE TITLE
Fix formatting for URL detail screen

### ISSUE THREAD

**Issue by kmcculloch** [edgi-govdata-archiving/archivers.space#6]
_From @dcwalk on February 1, 2017 3:45_

Small alignment issue in [AgencyForm.js](https://github.com/b5/pipeline/blob/182112a4815abe32863e73074a38913481e1ff72/imports/ui/components/form/AgencyForm.js):

<img width="393" alt="screen shot 2017-01-31 at 10 41 36 pm" src="https://cloud.githubusercontent.com/assets/4692834/22494571/82cd868e-e806-11e6-8b06-9b956d2f644b.png">

_Copied from original issue: b5/pipeline#6_

**Comment by kmcculloch** [comment]
_From @dcwalk on February 1, 2017 4:3_

Actually, some overflow on the URL as well depending on browser width

<img width="841" alt="screen shot 2017-01-31 at 10 46 31 pm" src="https://cloud.githubusercontent.com/assets/4692834/22494878/6f67d74a-e809-11e6-8df9-4668ec02be69.png">

**Comment by kmcculloch** [comment]
_From @b5 on February 1, 2017 19:30_

ugh yeah it's all gross. too much hustle. If you'd like to fix up any of the above, all the stylesheets live in client/scss :)

**Comment by b5** [comment]
No longer a thing
