### ISSUE TITLE
Add README instructions on setting up linter

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/archivers.space#61]
Per Code Walkthrough video comments 😄 , would be good to have details on setting up tools for  consistent development documented in the README.

Linter with rules is in package.json (eslint, babel-eslint) [ESlint](http://eslint.org/) 2015

**Comment by ChaiBapchya** [comment]
Do you want a documentation on How to setup ESLint? I would be happy to set it up myself and create a documentation of the same

**Comment by dcwalk** [comment]
@ChaiBapchya we are going to move our code base (and associated docs) to be publicly available ASAP and then your help will be definitely appreciated!

**Comment by dcwalk** [comment]
I spoke too soon! The code is open, documentation most welcome 👍

**Comment by ChaiBapchya** [comment]
Alright...working on it...Will setup ESLint and document the same

**Comment by kmcculloch** [comment]
@ChaiBapchya Thanks for the help! There's a bit of general info on linting over at https://github.com/edgi-govdata-archiving/overview/blob/master/protocol/linting.md, with some notes on archivers.space as an example. Feel free to copy & paste anything that would be helpful.

**Comment by kmcculloch** [comment]
Thanks again for the help @ChaiBapchya. I renamed your file, moved it to a "documentation" folder, and referenced it from our CONTRIBUTING.md file.
